<a href="https://colab.research.google.com/github/NATASHASAINI/python/blob/main/Regressiongit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()
data


{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [ ]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df['Price'] = data.target
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  Price  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422

In [ ]:
df.corr() #tocheck correlation exit between values

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
MedInc      1.000000 -0.119034  0.326895  -0.062040    0.004834  0.018766   
HouseAge   -0.119034  1.000000 -0.153277  -0.077747   -0.296244  0.013191   
AveRooms    0.326895 -0.153277  1.000000   0.847621   -0.072213 -0.004852   
AveBedrms  -0.062040 -0.077747  0.847621   1.000000   -0.066197 -0.006181   
Population  0.004834 -0.296244 -0.072213  -0.066197    1.000000  0.069863   
AveOccup    0.018766  0.013191 -0.004852  -0.006181    0.069863  1.000000   
Latitude   -0.079809  0.011173  0.106389   0.069721   -0.108785  0.002366   
Longitude  -0.015176 -0.108197 -0.027540   0.013344    0.099773  0.002476   
Price       0.688075  0.105623  0.151948  -0.046701   -0.024650 -0.023737   

            Latitude  Longitude     Price  
MedInc     -0.079809  -0.015176  0.688075  
HouseAge    0.011173  -0.108197  0.105623  
AveRooms    0.106389  -0.027540  0.151948  
AveBedrms   0.069721   0.013344 -0.046701  
Population -0.108785   0.099773 -0.024650  
AveOccup    0.002366   0.002476 -0.023737  
Latitude    1.000000  -0.924664 -0.144160  
Longitude  -0.924664   1.000000 -0.045967  
Price      -0.144160  -0.045967  1.000000

In [ ]:
!pip


Usage:   
  pip3 <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper c

In [ ]:
from statmodels.stats.outliers_influence import variance_inflation_factor
import numpy as np

In [ ]:
X = df.drop(columns=['Price'])
y = df['Price']

In [ ]:
X

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [ ]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Price, Length: 20640, dtype: float64

In [ ]:
X.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_scaled =scalar.fit_transform(X)
X_scaled

array([[ 2.34476576,  0.98214266,  0.62855945, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 2.33223796, -0.60701891,  0.32704136, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.7826994 ,  1.85618152,  1.15562047, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [-1.05458292, -0.84539315, -0.04021111, ..., -0.09122515,
         1.77823747, -0.87362627],
       [-0.78012947, -1.00430931, -0.07044252, ..., -0.04368215,
         1.75014627, -0.83369581]])

Check for Multicollinearity




In [ ]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor
import numpy as np

vif_data = pd.DataFrame()
vif_data['Features'] = X.columns
vif_data['VIF'] = [variance_inflation_factor(X_scaled, i) for i in range(X_scaled.shape[1])]
vif_data

Features       VIF
0      MedInc  2.501295
1    HouseAge  1.241254
2    AveRooms  8.342786
3   AveBedrms  6.994995
4  Population  1.138125
5    AveOccup  1.008324
6    Latitude  9.297624
7   Longitude  8.962263

In [ ]:
X = X[['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']]
X_scaled =scalar.fit_transform(X)
X_scaled

array([[ 2.34476576,  0.98214266,  0.62855945, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 2.33223796, -0.60701891,  0.32704136, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.7826994 ,  1.85618152,  1.15562047, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [-1.05458292, -0.84539315, -0.04021111, ..., -0.09122515,
         1.77823747, -0.87362627],
       [-0.78012947, -1.00430931, -0.07044252, ..., -0.04368215,
         1.75014627, -0.83369581]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y, test_size=0.2,random_state=1)

In [ ]:
X_train.shape

(16512, 8)

In [ ]:
y_test.shape

(4128,)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression() #initialize
model.fit(X_train,y_train)#train

y_pred = model.predict(X_test)

In [ ]:
model.intercept_

np.float64(2.0729129569208196)

In [ ]:
model.coef_

array([ 0.83317587,  0.12191612, -0.25905204,  0.2995942 , -0.00416386,
       -0.03580725, -0.9098169 , -0.88273692])

In [ ]:
model.predict(X_test)#test

array([2.12567705, 0.93977118, 2.70887192, ..., 2.9460839 , 2.63875476,
       1.46985176])

In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("Mean absolute error: %.2f" % mean_absolute_error(y_test, y_pred))
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("Root mean squared error: %.2f" % np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2-score: %.2f" % r2_score(y_test, y_pred))

Mean absolute error: 0.53
Mean squared error: 0.53
Root mean squared error: 0.73
R2-score: 0.60


Lasso, Ridge, ElasticNet Algo

In [ ]:
from sklearn.linear_model import Lasso, Ridge, ElasticNet


In [ ]:
from sklearn.linear_model import Lasso, Ridge, ElasticNet
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

lasso_model = Lasso()#initialize

lasso_model.fit(X_train,y_train)#fit or train

lasso_y_pred = lasso_model.predict(X_test)

#Evaluate the model
print('Mean Absolute Error: ===>',mean_absolute_error(y_test, lasso_y_pred))
print('Mean squared Error: ===>',mean_squared_error(y_test, lasso_y_pred))
print('root mean squared error: ===>',np.sqrt(mean_squared_error(y_test, lasso_y_pred)))
print("R2-score: %.2f" % r2_score(y_test, y_pred))

Mean Absolute Error: ===> 0.7615782541669575
Mean squared Error: ===> 0.9380337514945427
root mean squared error: ===> 0.9685214254184276
R2-score: -0.69


Ridge Model

In [ ]:
from sklearn.linear_model import Lasso, Ridge, ElasticNet

ridge_model = Ridge()#initialize

ridge_model.fit(X_train,y_train)#fit or train

ridge_y_pred = ridge_model.predict(X_test)

#Evaluate the model
print('Mean Absolute Error: ===>',mean_absolute_error(y_test, ridge_y_pred))
print('Mean squared Error: ===>',mean_squared_error(y_test, ridge_y_pred))
print('root mean squared error: ===>',np.sqrt(mean_squared_error(y_test, ridge_y_pred)))
print("R2-score: %.2f" % r2_score(y_test, ridge_y_pred))

Mean Absolute Error: ===> 0.5332039182571153
Mean squared Error: ===> 0.5558034669932211
root mean squared error: ===> 0.7455222779992702
R2-score: 0.58


ElasticNet Regressionn model

In [ ]:
from sklearn.linear_model import Lasso, Ridge, ElasticNet

ElasticNet_model =ElasticNet()#initialize

ElasticNet_model.fit(X_train,y_train)#fit or train

ElasticNet_y_pred = ElasticNet_model.predict(X_test)

#Evaluate the model
print('Mean Absolute Error: ===>',mean_absolute_error(y_test,ElasticNet_y_pred))
print('Mean squared Error: ===>',mean_squared_error(y_test,ElasticNet_y_pred))
print('root mean squared error: ===>',np.sqrt(mean_squared_error(y_test,ElasticNet_y_pred)))
print("R2-score: %.2f" % r2_score(y_test, ElasticNet_y_pred))

Mean Absolute Error: ===> 0.676283586138053
Mean squared Error: ===> 0.7645556403971131
root mean squared error: ===> 0.8743887238506185
R2-score: 0.42


DECISION TREE REGRESSOR

In [ ]:


from sklearn.tree import DecisionTreeRegressor


In [ ]:
dt_model =DecisionTreeRegressor()#initialize

dt_model.fit(X_train,y_train)#fit or train

dt_y_pred = dt_model.predict(X_test)

#Evaluate the model
print('Mean Absolute Error: ===>',mean_absolute_error(y_test,dt_y_pred))
print('Mean squared Error: ===>',mean_squared_error(y_test,dt_y_pred))
print('root mean squared error: ===>',np.sqrt(mean_squared_error(y_test,dt_y_pred)))
print("R2-score: %.2f" % r2_score(y_test, dt_y_pred))

Mean Absolute Error: ===> 0.4557014777131783
Mean squared Error: ===> 0.502279552276405
root mean squared error: ===> 0.7087168350451434
R2-score: 0.62


RANDOME FOREST REGRESSOR

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rf_model = RandomForestRegressor()#initialize

rf_model.fit(X_train,y_train)#fit or train

rf_y_pred = rf_model.predict(X_test)

#Evaluate the model
print('Mean Absolute Error: ===>',mean_absolute_error(y_test,rf_y_pred))
print('Mean squared Error: ===>',mean_squared_error(y_test,rf_y_pred))
print('root mean squared error: ===>',np.sqrt(mean_squared_error(y_test,rf_y_pred)))
print("R2-score: %.2f" % r2_score(y_test,rf_y_pred))

Mean Absolute Error: ===> 0.32670900249515517
Mean squared Error: ===> 0.25251511795195175
root mean squared error: ===> 0.5025088237553165
R2-score: 0.81



SVM


In [ ]:
from sklearn.svm import SVR

In [ ]:
svr_model = SVR()#initialize

svr_model.fit(X_train, y_train)#fit or train

svr_y_pred = svr_model.predict(X_test)

#Evaluate the model
print('Mean Absolute Error: ===>',mean_absolute_error(y_test, svr_y_pred))
print('Mean squared Error: ===>',mean_squared_error(y_test, svr_y_pred))
print('root mean squared error: ===>',np.sqrt(mean_squared_error(y_test, svr_y_pred)))
print("R2-score: %.2f" % r2_score(y_test, svr_y_pred))

Mean Absolute Error: ===> 0.8599506583445761
Mean squared Error: ===> 1.3320115421348744
root mean squared error: ===> 1.1541280440812771
R2-score: -0.02


Gradient boosing regressor algorithm




In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
gbr_model = GradientBoostingRegressor()#initialize

gbr_model.fit(X_train,y_train)#fit or train

gbr_y_pred = gbr_model.predict(X_test)

#Evaluate the model
print('Mean Absolute Error: ===>',mean_absolute_error(y_test, gbr_y_pred))
print('Mean squared Error: ===>',mean_squared_error(y_test, gbr_y_pred))
print('root mean squared error: ===>',np.sqrt(mean_squared_error(y_test, gbr_y_pred)))
print("R2-score: %.2f" % r2_score(y_test, gbr_y_pred))

Mean Absolute Error: ===> 0.37170104427631856
Mean squared Error: ===> 0.2940161448268125
root mean squared error: ===> 0.5422325560373634
R2-score: 0.78
